name: Deploy to Demo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies
        run: pnpm install
        env:
          GITHUB_AUTH_TOKEN: ${{secrets.PERSONAL_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy
        run: |
          echo "Deploying to demo..."
          pm2 start --name zhin npm -- run dev
          echo "Deployed to demo"
