name: CI Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release for Tag
        id: release_tag
        uses: lc-cn/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            body: |
              Please refer to [CHANGELOG.md](https://github.com/zhinjs/zhin/blob/main/CHANGELOG.md) for details.